# Generated by Django 3.1.7 on 2021-03-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_at',), 'verbose_name': 'Logs', 'verbose_name_plural': 'Logs'},
        ),
    ]
